name: Run Python Script

on:
  push:
    branches: [ main ]       # run on pushes to main
  schedule:
    - cron: '30 2 * * *'     # optional: daily at 02:30 UTC (remove if you don't want schedule)
  workflow_dispatch: {}      # allows manual run from Actions UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        env:
          MY_API_KEY: ${{ secrets.MY_API_KEY }}  # optional secret
        run: python scripts/hello.py
